import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState} from "react";

export default function Home() {
  const [link, setLink] = useState('')

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://github.com/vitalyliber/linkedin-proxy">Linkedin Proxy!</a>
        </h1>

        <p className={styles.description}>
          Past Linkedin link here 🔗
        </p>
        <input
          className={styles.input}
          value={link}
          onChange={(e) => setLink(e.target.value)}
        />
        <button onClick={() => {
          window.open(`/proxy/${link}`,'_blank');
        }} className={styles.button} disabled={link === ''} >Open via proxy</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://casply.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Casply
          </span>
        </a>
      </footer>
    </div>
  )
}
